---- Use a protected call so we don't error out on first use
--local status_ok, packer = pcall(require, "packer")
--if not status_ok then
--    return
--end
--
---- Have packer use a popup window
--packer.init {
--    display = {
--        open_fn = function()
--            return require("packer.util").float { border = "rounded" }
--        end
--    }
--}
--
--return require("packer").startup(function(use)
--    use { 'nvim-treesitter/nvim-treesitter', run = ':TSUpdate' }
--end)o